### ISSUE TITLE
Динамические YYEXTOPT_

### ISSUE THREAD

**Issue by ghost** [trumdu/gms-yagames#2]
Можно ли исправить зависимость этих переменных от имени расширения? Для единообразия я переименовал имя расширения в своём проекте, и у меня всё сломалось. Потратил много времени чтобы понять в чём дело((

Ну или хотябы в `readme` указать, что не стоит переименовывать

![image](https://github.com/user-attachments/assets/a05eb277-5399-4e9f-b617-996ffb7e7146)

**Comment by trumdu** [comment]
Нет, зависимость убрать нельзя.
Компилятор HTML использует имя расширения для получения доступа к параметрам расширения. Доступ идет по шаблону **${YYEXTOPT_MyExtName_CustomOption}**

[https://manual.gamemaker.io/lts/en/The_Asset_Editors/Extension_Creation/HTML5_Extensions.htm](https://manual.gamemaker.io/lts/en/The_Asset_Editors/Extension_Creation/HTML5_Extensions.htm)
